<?php

namespace Database\Seeders;

use App\Models\Supplier;
use Illuminate\Database\Seeder;

class SupplierSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $suppliers = [
            [
                'name' => 'Davao Food Supply',
                'contact_person' => 'Mark Santos',
                'phone' => '09170000001',
                'email' => 'davaofood@example.com',
                'address' => 'Davao City',
                'tax_number' => '100-000-001',
                'notes' => 'Food and beverage supplier',
                'is_active' => true,
            ],
            [
                'name' => 'Mindanao Beverage Trading',
                'contact_person' => 'John Garcia',
                'phone' => '09170000002',
                'email' => 'mindanaobeverage@example.com',
                'address' => 'Davao City',
                'tax_number' => '100-000-002',
                'notes' => 'Beverage supplier',
                'is_active' => true,
            ],
            [
                'name' => 'Southern Grocery Supply',
                'contact_person' => 'Ramon Cruz',
                'phone' => '09170000003',
                'email' => 'southerngrocery@example.com',
                'address' => 'General Santos City',
                'tax_number' => '100-000-003',
                'notes' => 'Grocery products supplier',
                'is_active' => true,
            ],
            [
                'name' => 'Koronadal Wholesale',
                'contact_person' => 'Pedro Dela Cruz',
                'phone' => '09170000004',
                'email' => 'koronadalwholesale@example.com',
                'address' => 'Koronadal City',
                'tax_number' => '100-000-004',
                'notes' => 'Wholesale supplier',
                'is_active' => true,
            ],
            [
                'name' => 'South Cotabato Trading',
                'contact_person' => 'Maria Reyes',
                'phone' => '09170000005',
                'email' => 'southcotabatotrading@example.com',
                'address' => 'South Cotabato',
                'tax_number' => '100-000-005',
                'notes' => 'General supplier',
                'is_active' => true,
            ],
            [
                'name' => 'Davao General Merchandise',
                'contact_person' => 'Ana Lopez',
                'phone' => '09170000006',
                'email' => 'davaogeneral@example.com',
                'address' => 'Davao City',
                'tax_number' => '100-000-006',
                'notes' => 'General merchandise',
                'is_active' => true,
            ],
            [
                'name' => 'Pacific Wholesale Center',
                'contact_person' => 'Carlos Mendoza',
                'phone' => '09170000007',
                'email' => 'pacificwholesale@example.com',
                'address' => 'Davao City',
                'tax_number' => '100-000-007',
                'notes' => 'Wholesale products',
                'is_active' => true,
            ],
            [
                'name' => 'Island Trading Company',
                'contact_person' => 'Joseph Tan',
                'phone' => '09170000008',
                'email' => 'islandtrading@example.com',
                'address' => 'Davao City',
                'tax_number' => '100-000-008',
                'notes' => 'Imported and local products',
                'is_active' => true,
            ],
            [
                'name' => 'Golden South Supplies',
                'contact_person' => 'Robert Flores',
                'phone' => '09170000009',
                'email' => 'goldensouth@example.com',
                'address' => 'General Santos City',
                'tax_number' => '100-000-009',
                'notes' => 'Retail supply',
                'is_active' => true,
            ],
            [
                'name' => 'Southern Star Distributors',
                'contact_person' => 'Daniel Torres',
                'phone' => '09170000010',
                'email' => 'southernstar@example.com',
                'address' => 'Koronadal City',
                'tax_number' => '100-000-010',
                'notes' => 'Food distributor',
                'is_active' => true,
            ],

            [
                'name' => 'Metro South Trading',
                'contact_person' => 'Michael Ramos',
                'phone' => '09170000011',
                'email' => 'metrosouth@example.com',
                'address' => 'Davao City',
                'tax_number' => '100-000-011',
                'notes' => 'General supplier',
                'is_active' => true,
            ],
            [
                'name' => 'Fresh Choice Supplies',
                'contact_person' => 'Grace Santos',
                'phone' => '09170000012',
                'email' => 'freshchoice@example.com',
                'address' => 'Davao City',
                'tax_number' => '100-000-012',
                'notes' => 'Fresh products',
                'is_active' => true,
            ],
            [
                'name' => 'Prime Grocery Distributor',
                'contact_person' => 'Anthony Garcia',
                'phone' => '09170000013',
                'email' => 'primegrocery@example.com',
                'address' => 'General Santos City',
                'tax_number' => '100-000-013',
                'notes' => 'Grocery distributor',
                'is_active' => true,
            ],
            [
                'name' => 'Blue Sky Trading',
                'contact_person' => 'Kevin Cruz',
                'phone' => '09170000014',
                'email' => 'bluesky@example.com',
                'address' => 'Davao City',
                'tax_number' => '100-000-014',
                'notes' => 'General merchandise',
                'is_active' => true,
            ],
            [
                'name' => 'Evergreen Supplies',
                'contact_person' => 'Linda Reyes',
                'phone' => '09170000015',
                'email' => 'evergreen@example.com',
                'address' => 'Koronadal City',
                'tax_number' => '100-000-015',
                'notes' => 'Retail products',
                'is_active' => true,
            ],
            [
                'name' => 'Central Mindanao Supply',
                'contact_person' => 'Francis Dela Cruz',
                'phone' => '09170000016',
                'email' => 'centralmindanao@example.com',
                'address' => 'South Cotabato',
                'tax_number' => '100-000-016',
                'notes' => 'General supplies',
                'is_active' => true,
            ],
            [
                'name' => 'East West Distributors',
                'contact_person' => 'William Tan',
                'phone' => '09170000017',
                'email' => 'eastwest@example.com',
                'address' => 'Davao City',
                'tax_number' => '100-000-017',
                'notes' => 'Wholesale distributor',
                'is_active' => true,
            ],
            [
                'name' => 'Value Mart Supplier',
                'contact_person' => 'Susan Lim',
                'phone' => '09170000018',
                'email' => 'valuemart@example.com',
                'address' => 'General Santos City',
                'tax_number' => '100-000-018',
                'notes' => 'Value products supplier',
                'is_active' => true,
            ],
            [
                'name' => 'Reliable Trade Supply',
                'contact_person' => 'George Mendoza',
                'phone' => '09170000019',
                'email' => 'reliabletrade@example.com',
                'address' => 'Davao City',
                'tax_number' => '100-000-019',
                'notes' => 'Reliable wholesale supplier',
                'is_active' => true,
            ],
            [
                'name' => 'South Pacific Goods',
                'contact_person' => 'Helen Flores',
                'phone' => '09170000020',
                'email' => 'southpacific@example.com',
                'address' => 'Koronadal City',
                'tax_number' => '100-000-020',
                'notes' => 'General goods',
                'is_active' => true,
            ],

            [
                'name' => 'Davao Prime Foods',
                'contact_person' => 'Mark Villanueva',
                'phone' => '09170000021',
                'email' => 'davaoprimefoods@example.com',
                'address' => 'Davao City',
                'tax_number' => '100-000-021',
                'notes' => 'Food supplier',
                'is_active' => true,
            ],
            [
                'name' => 'Mindanao Fresh Market',
                'contact_person' => 'Jenny Garcia',
                'phone' => '09170000022',
                'email' => 'mindanaofresh@example.com',
                'address' => 'Davao City',
                'tax_number' => '100-000-022',
                'notes' => 'Fresh market supplier',
                'is_active' => true,
            ],
            [
                'name' => 'Golden Harvest Trading',
                'contact_person' => 'Eric Santos',
                'phone' => '09170000023',
                'email' => 'goldenharvest@example.com',
                'address' => 'General Santos City',
                'tax_number' => '100-000-023',
                'notes' => 'Food products',
                'is_active' => true,
            ],
            [
                'name' => 'Southland Distribution',
                'contact_person' => 'Rose Cruz',
                'phone' => '09170000024',
                'email' => 'southlanddistribution@example.com',
                'address' => 'Koronadal City',
                'tax_number' => '100-000-024',
                'notes' => 'Distribution company',
                'is_active' => true,
            ],
            [
                'name' => 'Prime Value Trading',
                'contact_person' => 'Victor Reyes',
                'phone' => '09170000025',
                'email' => 'primevalue@example.com',
                'address' => 'Davao City',
                'tax_number' => '100-000-025',
                'notes' => 'General products',
                'is_active' => true,
            ],
            [
                'name' => 'Family Choice Supplier',
                'contact_person' => 'Catherine Lopez',
                'phone' => '09170000026',
                'email' => 'familychoice@example.com',
                'address' => 'Davao City',
                'tax_number' => '100-000-026',
                'notes' => 'Household products',
                'is_active' => true,
            ],
            [
                'name' => 'Quality First Trading',
                'contact_person' => 'Rene Torres',
                'phone' => '09170000027',
                'email' => 'qualityfirst@example.com',
                'address' => 'General Santos City',
                'tax_number' => '100-000-027',
                'notes' => 'Quality products',
                'is_active' => true,
            ],
            [
                'name' => 'Best Buy Wholesale',
                'contact_person' => 'Patricia Ramos',
                'phone' => '09170000028',
                'email' => 'bestbuywholesale@example.com',
                'address' => 'Davao City',
                'tax_number' => '100-000-028',
                'notes' => 'Wholesale supplier',
                'is_active' => true,
            ],
            [
                'name' => 'Direct Source Trading',
                'contact_person' => 'Andrew Tan',
                'phone' => '09170000029',
                'email' => 'directsource@example.com',
                'address' => 'Koronadal City',
                'tax_number' => '100-000-029',
                'notes' => 'Direct supplier',
                'is_active' => true,
            ],
            [
                'name' => 'Southern Choice Supply',
                'contact_person' => 'Michelle Lim',
                'phone' => '09170000030',
                'email' => 'southernchoice@example.com',
                'address' => 'South Cotabato',
                'tax_number' => '100-000-030',
                'notes' => 'Retail supply',
                'is_active' => true,
            ],

            [
                'name' => 'Davao Market Supply',
                'contact_person' => 'Brian Santos',
                'phone' => '09170000031',
                'email' => 'davaomarket@example.com',
                'address' => 'Davao City',
                'tax_number' => '100-000-031',
                'notes' => 'Market supplier',
                'is_active' => true,
            ],
            [
                'name' => 'Mindanao Trade Hub',
                'contact_person' => 'Laura Garcia',
                'phone' => '09170000032',
                'email' => 'mindanaotrade@example.com',
                'address' => 'Davao City',
                'tax_number' => '100-000-032',
                'notes' => 'Trading supplier',
                'is_active' => true,
            ],
            [
                'name' => 'South Central Supplies',
                'contact_person' => 'Paul Cruz',
                'phone' => '09170000033',
                'email' => 'southcentral@example.com',
                'address' => 'General Santos City',
                'tax_number' => '100-000-033',
                'notes' => 'General supplies',
                'is_active' => true,
            ],
            [
                'name' => 'Reliable Goods Trading',
                'contact_person' => 'Nancy Reyes',
                'phone' => '09170000034',
                'email' => 'reliablegoods@example.com',
                'address' => 'Koronadal City',
                'tax_number' => '100-000-034',
                'notes' => 'General goods',
                'is_active' => true,
            ],
            [
                'name' => 'First Choice Distributor',
                'contact_person' => 'Edward Flores',
                'phone' => '09170000035',
                'email' => 'firstchoice@example.com',
                'address' => 'Davao City',
                'tax_number' => '100-000-035',
                'notes' => 'Distributor',
                'is_active' => true,
            ],
            [
                'name' => 'Green Valley Supply',
                'contact_person' => 'Sarah Mendoza',
                'phone' => '09170000036',
                'email' => 'greenvalley@example.com',
                'address' => 'Davao City',
                'tax_number' => '100-000-036',
                'notes' => 'Food and household products',
                'is_active' => true,
            ],
            [
                'name' => 'Pacific South Trading',
                'contact_person' => 'Thomas Garcia',
                'phone' => '09170000037',
                'email' => 'pacificsouth@example.com',
                'address' => 'General Santos City',
                'tax_number' => '100-000-037',
                'notes' => 'General supplier',
                'is_active' => true,
            ],
            [
                'name' => 'Affordable Goods Supplier',
                'contact_person' => 'Angela Santos',
                'phone' => '09170000038',
                'email' => 'affordablegoods@example.com',
                'address' => 'Koronadal City',
                'tax_number' => '100-000-038',
                'notes' => 'Affordable products',
                'is_active' => true,
            ],
            [
                'name' => 'Market Link Trading',
                'contact_person' => 'Ronald Cruz',
                'phone' => '09170000039',
                'email' => 'marketlink@example.com',
                'address' => 'Davao City',
                'tax_number' => '100-000-039',
                'notes' => 'Market distributor',
                'is_active' => true,
            ],
            [
                'name' => 'Southern Wholesale Hub',
                'contact_person' => 'Christine Reyes',
                'phone' => '09170000040',
                'email' => 'southernwholesale@example.com',
                'address' => 'South Cotabato',
                'tax_number' => '100-000-040',
                'notes' => 'Wholesale products',
                'is_active' => true,
            ],

            [
                'name' => 'Davao Direct Supply',
                'contact_person' => 'Jason Lopez',
                'phone' => '09170000041',
                'email' => 'davaodirect@example.com',
                'address' => 'Davao City',
                'tax_number' => '100-000-041',
                'notes' => 'Direct supplier',
                'is_active' => true,
            ],
            [
                'name' => 'South Mindanao Foods',
                'contact_person' => 'Monica Torres',
                'phone' => '09170000042',
                'email' => 'southmindanaofoods@example.com',
                'address' => 'General Santos City',
                'tax_number' => '100-000-042',
                'notes' => 'Food supplier',
                'is_active' => true,
            ],
            [
                'name' => 'Prime Source Distribution',
                'contact_person' => 'Steven Ramos',
                'phone' => '09170000043',
                'email' => 'primesource@example.com',
                'address' => 'Davao City',
                'tax_number' => '100-000-043',
                'notes' => 'Distribution supplier',
                'is_active' => true,
            ],
            [
                'name' => 'Good Choice Trading',
                'contact_person' => 'Elizabeth Tan',
                'phone' => '09170000044',
                'email' => 'goodchoice@example.com',
                'address' => 'Koronadal City',
                'tax_number' => '100-000-044',
                'notes' => 'General merchandise',
                'is_active' => true,
            ],
            [
                'name' => 'Southern Star Supply',
                'contact_person' => 'Kenneth Lim',
                'phone' => '09170000045',
                'email' => 'southernstarsupply@example.com',
                'address' => 'South Cotabato',
                'tax_number' => '100-000-045',
                'notes' => 'Retail supplier',
                'is_active' => true,
            ],
            [
                'name' => 'Davao Central Trading',
                'contact_person' => 'Rebecca Santos',
                'phone' => '09170000046',
                'email' => 'davaocentral@example.com',
                'address' => 'Davao City',
                'tax_number' => '100-000-046',
                'notes' => 'General supplier',
                'is_active' => true,
            ],
            [
                'name' => 'Mindanao Choice Distributor',
                'contact_person' => 'Christopher Garcia',
                'phone' => '09170000047',
                'email' => 'mindanaochoice@example.com',
                'address' => 'General Santos City',
                'tax_number' => '100-000-047',
                'notes' => 'Distributor',
                'is_active' => true,
            ],
            [
                'name' => 'Value Plus Trading',
                'contact_person' => 'Jessica Cruz',
                'phone' => '09170000048',
                'email' => 'valueplus@example.com',
                'address' => 'Koronadal City',
                'tax_number' => '100-000-048',
                'notes' => 'Value products',
                'is_active' => true,
            ],
            [
                'name' => 'Southland General Supply',
                'contact_person' => 'Daniel Reyes',
                'phone' => '09170000049',
                'email' => 'southlandgeneral@example.com',
                'address' => 'Davao City',
                'tax_number' => '100-000-049',
                'notes' => 'General merchandise',
                'is_active' => true,
            ],
            [
                'name' => 'Golden Gate Wholesale',
                'contact_person' => 'Maria Flores',
                'phone' => '09170000050',
                'email' => 'goldengate@example.com',
                'address' => 'General Santos City',
                'tax_number' => '100-000-050',
                'notes' => 'Wholesale supplier',
                'is_active' => true,
            ],
        ];

        foreach ($suppliers as $supplier) {
            Supplier::create($supplier);
        }
    }
}
